[package]
name = "web-spectrogram"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = "0.3"
kofft = { path = "..", features = ["wasm"], default-features = true }
