[package]
name = "sanity-check"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
claxon = "0.4"
image = { version = "0.24", default-features = false, features = ["png"] }
rustfft = "6"
num-complex = "0.4"
kofft = { path = ".." }
