name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=native"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run benchmarks (SIMD enabled)
        run: cargo bench --bench bench_fft --features "parallel x86_64" -- --sample-size=10 --measurement-time=0.5 --warm-up-time=0.2
      - name: SIMD speedup example
        run: cargo run --example simd_speedup --features x86_64 --release
      - name: Update README
        run: cargo run --example update_bench_readme
      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ -n "$(git status --porcelain README.md benchmarks/latest.json)" ]]; then
            git add README.md benchmarks/latest.json
            git commit -m "chore: update benchmark results"
            git push
          fi
