name: Build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        features:
          - ""
          - "--no-default-features"
          - "--features sse,std"
          - "--features parallel"
          - "--all-features"
        include:
          - os: ubuntu-latest
            target: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
          - os: macos-latest
            target: ""
        exclude:
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
            features: "--all-features"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          targets: ${{ matrix.target }}
      - name: Build
        shell: bash
        run: |
          TARGET_ARG=""
          if [ -n "${{ matrix.target }}" ]; then
            TARGET_ARG="--target ${{ matrix.target }}"
          fi
          cargo build --all-targets ${{ matrix.features }} $TARGET_ARG
          cargo bench --no-run ${{ matrix.features }} $TARGET_ARG
