name: Publish

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - name: Ensure tag matches version
        run: |
          version=$(grep '^version = ' Cargo.toml | head -n 1 | cut -d '"' -f2)
          tag=${GITHUB_REF_NAME}
          if [ "v$version" != "$tag" ]; then
            echo "Version mismatch: Cargo.toml has $version but tag is $tag"
            exit 1
          fi
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --all --verbose
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked
