name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        features:
          - ''
          - '--no-default-features'
          - '--features "sse std internal-tests"'
          - '--features "parallel internal-tests"'
          - '--features "simd soa internal-tests"'
          - '--all-features'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run tests
        shell: bash
        run: cargo test --all --verbose ${{ matrix.features }}
  feature-checks:
    name: Feature checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - '--features "avx2"'
          - '--features "avx512"'
          - '--features "wasm"'
          - '--features "aarch64"'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run checks
        shell: bash
        run: cargo check --all --verbose ${{ matrix.features }}
